////////////////////////////////////////////////////////////////////////////////
//
//  ADOBE SYSTEMS INCORPORATED
//  Copyright 2004-2007 Adobe Systems Incorporated
//  All Rights Reserved.
//
//  NOTICE: Adobe permits you to use, modify, and distribute this file
//  in accordance with the terms of the license agreement accompanying it.
//
////////////////////////////////////////////////////////////////////////////////

/* this file is generated by apivergen.abc. do no edit */
/*
[0,player,full]=660:FP_9_0
[0,air,full]=661:AIR_1_0
[1,player,full]=662:FP_10_0
[1,air,full]=663:AIR_1_5
[2,air,full]=664:AIR_1_5_1
[3,player,full]=665:FP_10_0_32
[3,air,full]=666:AIR_1_5_2
[4,player,full]=667:FP_10_1
[4,player,system]=669:FP_SYS
[4,air,full]=668:AIR_2_0
[5,player,system]=670:FP_SYS
[5,air,full]=669:AIR_2_5
[5,air,system]=671:AIR_SYS
*/

package macromedia.asc.util;
public class APIVersions {
public static int min_version_num = 660;
public static int max_version_num = 670;
public static int versions [][] = {
  {660, 661, 662, 663, 664, 665, 666, 667, 668, 670, 669, 671, },
  {661, 663, 664, 666, 668, 669, 671, },
  {662, 663, 664, 665, 666, 667, 668, 670, 669, 671, },
  {663, 664, 666, 668, 669, 671, },
  {664, 666, 668, 669, 671, },
  {665, 666, 667, 668, 670, 669, 671, },
  {666, 668, 669, 671, },
  {667, 668, 670, 669, 671, },
  {668, 669, 671, },
  {669, 671, },
  {670, 671, },
  {671, },
};
public static String uris [] = {
  "",
  "__AS3__.vec",
  "adobe.utils",
  "avmplus",
  "flash.accessibility",
  "flash.automation",
  "flash.data",
  "flash.debugger",
  "flash.desktop",
  "flash.display",
  "flash.errors",
  "flash.events",
  "flash.external",
  "flash.filesystem",
  "flash.filters",
  "flash.geom",
  "flash.globalization",
  "flash.html",
  "flash.html.script",
  "flash.media",
  "flash.net",
  "flash.net.dns",
  "flash.net.drm",
  "flash.printing",
  "flash.profiler",
  "flash.sampler",
  "flash.security",
  "flash.sensors",
  "flash.system",
  "flash.text",
  "flash.text.engine",
  "flash.text.ime",
  "flash.ui",
  "flash.utils",
  "flash.xml",
};
public static int api_compat [] = {0xfff, 0xb5a, 0xffc, 0xb58, 0xb50, 0xfe0, 0xb40, 0xf80, 0xb00, 0xa00, 0xc00, 0x800, };
};
