////////////////////////////////////////////////////////////////////////////////
//
//  ADOBE SYSTEMS INCORPORATED
//  Copyright 2004-2007 Adobe Systems Incorporated
//  All Rights Reserved.
//
//  NOTICE: Adobe permits you to use, modify, and distribute this file
//  in accordance with the terms of the license agreement accompanying it.
//
////////////////////////////////////////////////////////////////////////////////

/* this file is generated by abcvergen.abc. do no edit */
/*
[0,player,full]=660:FP_9_0
[0,air,full]=661:AIR_1_0
[1,player,full]=662:FP_10_0
[1,air,full]=663:AIR_1_5
[2,air,full]=664:AIR_1_5_1
[3,player,full]=665:FP_10_0_32
[3,air,full]=666:AIR_1_5_2
[4,player,full]=667:FP_10_1
[4,air,full]=668:AIR_2_0
*/

package macromedia.asc.util;
public class APIVersions {
public static int min_version_num = 660;
public static int max_version_num = 668;
public static int versions [][] = {
  {660, 661, 662, 663, 664, 665, 666, 667, 668, },
  {661, 663, 664, 666, 668, },
  {662, 663, 664, 665, 666, 667, 668, },
  {663, 664, 666, 668, },
  {664, 666, 668, },
  {665, 666, 667, 668, },
  {666, 668, },
  {667, 668, },
  {668, },
};
public static String uris [] = {
  "",
  "adobe.utils",
  "flash.accessibility",
  "flash.automation",
  "flash.data",
  "flash.debugger",
  "flash.desktop",
  "flash.display",
  "flash.errors",
  "flash.events",
  "flash.external",
  "flash.filesystem",
  "flash.filters",
  "flash.geom",
  "flash.globalization",
  "flash.html",
  "flash.media",
  "flash.net",
  "flash.net.dns",
  "flash.net.drm",
  "flash.printing",
  "flash.profiler",
  "flash.security",
  "flash.system",
  "flash.text",
  "flash.text.engine",
  "flash.text.ime",
  "flash.ui",
  "flash.utils",
  "flash.xml",
  "avmplus",
  "__AS3__.vec",
};
};
